---
- name: Reload Systemd
  systemd:
    daemon_reload: yes

- name: Start Redis
  service:
    name: redis
    state: started

- name: Restart Redis
  service:
    name: redis
    state: restarted

