---
- name: Install PHP
  apt:
    name: php5-cli
    state: present
  when: ansible_distribution_release == 'trusty'

- name: Install PHP 7
  apt:
    name: php-cli
    state: present
  when: ansible_distribution_release == 'xenial' or ansible_distribution_release == 'bionic' or ansible_distribution_release == 'stretch'

- name: Install PHP5-FPM
  apt:
    name: php5-fpm
    state: present
  when: ansible_distribution_release == 'trusty'

- name: Install PHP-FPM
  apt:
    name: php-fpm
    state: present
  when: ansible_distribution_release == 'xenial' or ansible_distribution_release == 'bionic' or ansible_distribution_release == 'stretch'

- name: Include Debian Vars
  include_vars: Debian.yml
  when: ansible_distribution_release == 'trusty'

- name: Include Debian Vars 1604
  include_vars: Debian1604.yml
  when: ansible_distribution_release == 'xenial' or ansible_distribution_release == 'bionic' or ansible_distribution_release == 'stretch'

- name: Include Ubuntu vars 1804
  include_vars: Ubuntu1804.yml
  when: ansible_distribution_release == 'bionic'

- name: Install other packages
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ phpfpm_pkgs }}'

- name: Install PECL packages
  shell: "yes '' | pecl install {{ item }}"
  with_items: '{{ phpfpm_pkgs_pecl }}'
  register: pecl_result
  changed_when: "not 'is already installed and is the same as the released version' in pecl_result.stdout"
  failed_when: "'No valid packages found' in pecl_result.stdout"

- name: Enable PHP modules
  shell: 'php5enmod {{ item }}'
  with_items: '{{ phpfpm_modules_enable }}'
  when: ansible_distribution_release == 'trusty'

- name: Enable PHP modules 1604
  shell: 'phpenmod {{ item }}'
  with_items: '{{ phpfpm_modules_enable }}'
  when: ansible_distribution_release == 'xenial' or ansible_distribution_release == 'bionic' or ansible_distribution_release == 'stretch'

- name: Enable PHP modules
  copy:
    src: '/etc/php5/mods-available/{{ item }}.ini'
    dest: '/etc/php5/fpm/conf.d/{{ item }}.ini'
  with_items: '{{ phpfpm_modules_enable }}'
  when: ansible_distribution_release == 'trusty'

- name: Enable PHP modules
  copy:
    src: '/etc/php/7.0/mods-available/{{ item }}.ini'
    dest: '/etc/php/7.0/fpm/conf.d/{{ item }}.ini'
  with_items: '{{ phpfpm_modules_enable }}'
  when: ansible_distribution_release == 'xenial' or ansible_distribution_release == 'stretch'

- name: Enable PHP modules
  copy:
    src: '/etc/php/7.2/mods-available/{{ item }}.ini'
    dest: '/etc/php/7.2/fpm/conf.d/{{ item }}.ini'
  with_items: '{{ phpfpm_modules_enable }}'
  when: ansible_distribution_release == 'bionic'
