---
- include: install_debian.yml
  when: ansible_os_family == 'Debian'

- include: install_redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Configure PHP
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ php_modules_config }}"

- name: Optimize opcache module
  ini_file:
    dest: "{{ php_modules_config_root }}/10-opcache.ini"
    section: null
    option: opcache.memory_consumption
    value: "{{ php_opcache_memory_consumption }}"
    state: present

- name: Restart Apache
  service:
    name: "{{ apache_pkg }}"
    state: restarted
  when: apache_pkg is defined
